# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)



platform :ios do

   desc "Push a new beta build to TestFlight"
   lane :pushToTestflight do
    increment_build_number(xcodeproj: "NY Times Articles.xcodeproj")
    build_app(workspace: "NY Times Articles.xcworkspace", scheme: "NY Times Articles")
    upload_to_testflight
   end


   desc "Run tests"
   lane :runTests do
     run_tests(project: 'NY Times Articles.xcworkspace',
               scheme: 'NY Times Articles',
               device: 'iPhone 12',
               clean: true)
   end

end

